--INTITUTO NACIONAL DE APRENDIZAJE
--MODULO: JAVA
--DOCENTE: LUIS ALONSO BOGANTES RODRIGUEZ
--ESTUDIANTE: DUNIER JAVIER BOLANOS RAMIREZ
--FASE I SQL SCRIPT PARA PROYECTO DE COFFE SHOP

CREATE DATABASE COFFEE_SHOP_DB
GO

USE COFFEE_SHOP_DB
GO


CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT CONSTRAINT PK_ID_PRODUCTOS PRIMARY KEY NOT NULL IDENTITY,
    NOMBRE_PRODUCTO VARCHAR(255),
    DESCRIPCION VARCHAR(255),
    CANTIDAD_EN_STOCK DECIMAL(10,2),
	UNIDAD VARCHAR(20),
    PRECIO_UNITARIO DECIMAL(10, 2)
);

CREATE TABLE EMPLEADOS (
    ID_EMPLEADO INT CONSTRAINT PK_ID_EMPLEADOS PRIMARY KEY NOT NULL IDENTITY,
    NOMBRE_EMPLEADO VARCHAR(255),
    DIRECCION VARCHAR(255),
    NUMERO_TELEFONO VARCHAR(15),
    CORREO_ELECTRONICO VARCHAR(255) UNIQUE,
    CARGO VARCHAR(255),
);

CREATE TABLE CLIENTES (
    ID_CLIENTE INT CONSTRAINT PK_ID_CLIENTES PRIMARY KEY NOT NULL IDENTITY,
    NOMBRE_CLIENTE VARCHAR(255),
    DIRECCION VARCHAR(255),
    NUMERO_TELEFONO VARCHAR(15),
    CORREO_ELECTRONICO VARCHAR(255) UNIQUE
);

CREATE TABLE PEDIDOS (
    ID_PEDIDO INT CONSTRAINT PK_ID_PEDIDOS PRIMARY KEY NOT NULL IDENTITY, 
	ID_PRODUCTO INT,
	CANTIDAD INT,
    FECHA DATE,
	HORA TIME,
    ESTADO_PEDIDO VARCHAR(255), 
);

CREATE TABLE FACTURACION (
    ID_FACTURA INT CONSTRAINT PK_ID_FACTURACION PRIMARY KEY NOT NULL IDENTITY,
    FECHA DATE,
	HORA TIME,
    TOTAL_FACTURA DECIMAL(10, 2),  
);

CREATE TABLE PAGOS (
    ID_PAGO INT CONSTRAINT PK_ID_PAGOS PRIMARY KEY NOT NULL IDENTITY,
    ID_FACTURA INT,
    METODO_PAGO VARCHAR(255),
    FECHA DATE,
	HORA TIME,
	ESTADO_PAGO VARCHAR(255),
    FOREIGN KEY (ID_FACTURA) REFERENCES FACTURACION(ID_FACTURA)
);

CREATE TABLE DETALLES_TRANSACCION (
    ID_DETALLE_PEDIDO INT CONSTRAINT PK_ID_DETALLES_TRANSACCIONI PRIMARY KEY NOT NULL IDENTITY,
	ID_CLIENTE INT,
	ID_FACTURA INT,
    ID_PEDIDO INT,
	ID_EMPLEADO INT, 
);

--LLAVES FORANEAS

ALTER TABLE PEDIDOS
ADD CONSTRAINT FK_ID_PRODUCTO_PEDIDOS 
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
ON DELETE CASCADE
GO
ALTER TABLE DETALLES_TRANSACCION
ADD CONSTRAINT FK_ID_PEDIDO_DT
FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
ON DELETE CASCADE
GO
ALTER TABLE DETALLES_TRANSACCION
ADD CONSTRAINT FK_ID_EMPLEADO_DT
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
ON DELETE CASCADE
GO
ALTER TABLE DETALLES_TRANSACCION
ADD CONSTRAINT FK_ID_CLIENTE_DT
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
ON DELETE CASCADE
GO
ALTER TABLE DETALLES_TRANSACCION
ADD CONSTRAINT FK_ID_FACTURA_DT
FOREIGN KEY (ID_FACTURA) REFERENCES FACTURACION(ID_FACTURA)
ON DELETE CASCADE
GO

--RESTRICCIONES PARA PRODUCTOS
ALTER TABLE PRODUCTOS
ADD CONSTRAINT CK_CANTIDAD_STOCK CHECK (CANTIDAD_EN_STOCK >= 0)
ALTER TABLE PRODUCTOS
ADD CONSTRAINT CK_UNIDAD_PRODUCTOS CHECK (UNIDAD IN('Onzas', 'Gramos', 'Kilos', 'Libras', 'Unidades'))
ALTER TABLE PRODUCTOS
ADD CONSTRAINT CK_PRECIO CHECK (PRECIO_UNITARIO >= 0)

--RESTRICCIONES PARA PEDIDOS
ALTER TABLE PEDIDOS
ADD CONSTRAINT CK_CANTIDAD CHECK (CANTIDAD >= 0)
ALTER TABLE PEDIDOS
ADD CONSTRAINT DF_FECHA_PEDIDOS DEFAULT CAST(GETDATE() AS DATE) FOR FECHA
ALTER TABLE PEDIDOS
ADD CONSTRAINT DF_HORA_PEDIDOS DEFAULT (CAST(GETDATE() AS TIME)) FOR HORA
ALTER TABLE PRODUCTOS
ADD CONSTRAINT CK_UNIDAD_PEDIDOS CHECK (UNIDAD IN('Esperando', 'Servido', 'Cancelado'))

--RESTRICCIONES PARA FACTURACIÓN
ALTER TABLE FACTURACION
ADD CONSTRAINT DF_FECHA_FACTURA DEFAULT CAST(GETDATE() AS DATE) FOR FECHA
ALTER TABLE FACTURACION
ADD CONSTRAINT DF_HORA_FACTURA DEFAULT CAST(GETDATE() AS TIME) FOR HORA
ALTER TABLE FACTURACION
ADD CONSTRAINT CK_TOTAL_FACTURA CHECK (TOTAL_FACTURA >= 0);
 
 --RESTRICCIONES PARA PAGOS
 ALTER TABLE PAGOS
ADD CONSTRAINT CK_METODO_PAGO CHECK (METODO_PAGO IN ('EFECTIVO', 'TARJETA', 'SINPE'));
ALTER TABLE PAGOS
ADD CONSTRAINT DF_FECHA_PAGOS DEFAULT CAST(GETDATE() AS DATE) FOR FECHA;
ALTER TABLE PAGOS
ADD CONSTRAINT DF_HORA_PAGOS DEFAULT CAST(GETDATE() AS TIME) FOR HORA;
ALTER TABLE PAGOS
ADD CONSTRAINT CK_ESTADO_PAGO CHECK (ESTADO_PAGO IN ('PAGADO', 'DEBE'));

SELECT * FROM PRODUCTOS
SELECT * FROM EMPLEADOS
SELECT * FROM CLIENTES
SELECT * FROM PEDIDOS
SELECT * FROM FACTURACION
SELECT * FROM PAGOS
SELECT * FROM DETALLES_TRANSACCION