--INTITUTO NACIONAL DE APRENDIZAJE
--MODULO: JAVA
--DOCENTE: LUIS ALONSO BOGANTES RODRIGUEZ
--ESTUDIANTE: DUNIER JAVIER BOLANOS RAMIREZ
--FASE I SQL SCRIPT PARA PROYECTO DE COFFE SHOP

CREATE DATABASE COFFEE_SHOP_DB
GO

USE COFFEE_SHOP_DB
GO

CREATE TABLE CARGOS (
    ID_CARGO INT CONSTRAINT PK_ID_ROL PRIMARY KEY,
	CARGO VARCHAR(255)
);

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT CONSTRAINT PK_ID_PRODUCTOS PRIMARY KEY NOT NULL IDENTITY(10001,1),
    NOMBRE_PRODUCTO VARCHAR(255),
    DESCRIPCION VARCHAR(255),
    CANTIDAD_EN_STOCK DECIMAL(10,2),
	UNIDAD VARCHAR(20),
    PRECIO_UNITARIO DECIMAL(10, 2)
);

CREATE TABLE EMPLEADOS (
    ID_EMPLEADO INT CONSTRAINT PK_ID_EMPLEADOS PRIMARY KEY NOT NULL IDENTITY(1,1),
    NOMBRE_EMPLEADO VARCHAR(255),
    DIRECCION VARCHAR(255),
    NUMERO_TELEFONO VARCHAR(15),
    CORREO_ELECTRONICO VARCHAR(255) UNIQUE,   
	ID_CARGO INT
);

CREATE TABLE CLIENTES (
    ID_CLIENTE INT CONSTRAINT PK_ID_CLIENTES PRIMARY KEY NOT NULL IDENTITY(101,1),
    NOMBRE_CLIENTE VARCHAR(255),
    DIRECCION VARCHAR(255),
    NUMERO_TELEFONO VARCHAR(15),
    CORREO_ELECTRONICO VARCHAR(255) UNIQUE
);


CREATE TABLE DETALLE_FACTURA (
    ID_FACTURA INT, 
	ID_PRODUCTO INT,
	CANTIDAD INT,
	SUB_TOTAL DECIMAL(10,2),
	CONSTRAINT PK_DETALLE_FACTURA PRIMARY KEY (ID_FACTURA,ID_PRODUCTO)
);

CREATE TABLE ENCABEZADO_FACTURA (
    ID_FACTURA INT CONSTRAINT PK_ID_ENCABEZADO_FACTURA PRIMARY KEY NOT NULL IDENTITY(990001,1),
    ID_CLIENTE INT,
    FECHA VARCHAR(255),
	IMPUESTO DECIMAL(10,2),
	DESCUENTO DECIMAL(10,2),
    TOTAL DECIMAL(10, 2) 
);

CREATE TABLE PAGOS (
    ID_PAGO INT CONSTRAINT PK_ID_PAGOS PRIMARY KEY NOT NULL IDENTITY(1,1),
    ID_FACTURA INT,
    METODO_PAGO VARCHAR(255),
	HORA VARCHAR(255),
	ESTADO_PAGO VARCHAR(255)
);

CREATE TABLE REGISTRO_SISTEMA (
    ID_REGISTRO_SISTEMA INT CONSTRAINT PK_ID_REGISTRO_SISTEMA PRIMARY KEY NOT NULL IDENTITY(1,1),
	ID_FACTURA INT,
	ID_EMPLEADO INT
);

--LLAVES FORANEAS
ALTER TABLE EMPLEADOS
ADD CONSTRAINT FK_ID_CARGO
FOREIGN KEY (ID_CARGO) REFERENCES CARGOS(ID_CARGO)
GO
ALTER TABLE DETALLE_FACTURA ADD CONSTRAINT FK_DETALLE_FACTURA
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
ON DELETE CASCADE
GO
ALTER TABLE DETALLE_FACTURA ADD CONSTRAINT FK_DETALLE_FACTURA_ENCABEZADO
FOREIGN KEY (ID_FACTURA) REFERENCES ENCABEZADO_FACTURA(ID_FACTURA)
ON DELETE CASCADE
GO
ALTER TABLE ENCABEZADO_FACTURA
ADD CONSTRAINT FK_CLIENTES_EF
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
ON DELETE CASCADE
GO
ALTER TABLE REGISTRO_SISTEMA
ADD CONSTRAINT FK_ID_EMPLEADO_DT
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
ON DELETE CASCADE
GO
ALTER TABLE REGISTRO_SISTEMA
ADD CONSTRAINT FK_ID_ENCABEZADO_FACTURA_RS
FOREIGN KEY (ID_FACTURA) REFERENCES ENCABEZADO_FACTURA(ID_FACTURA)
ON DELETE CASCADE
GO
ALTER TABLE PAGOS
ADD CONSTRAINT FK_ID_ENCABEZADO_FACTURA_PGS
FOREIGN KEY (ID_FACTURA) REFERENCES ENCABEZADO_FACTURA(ID_FACTURA)
ON DELETE CASCADE
GO

--RESTRICCIONES PARA PRODUCTOS

ALTER TABLE PRODUCTOS
ADD CONSTRAINT CK_UNIDAD_PRODUCTOS CHECK (UNIDAD IN('Onza', 'Gramo', 'Kilo', 'Libra', 'Unidad','Litro'))
ALTER TABLE PRODUCTOS
ADD CONSTRAINT CK_PRECIO CHECK (PRECIO_UNITARIO >= 0)

--RESTRICCIONES PARA DETALLE_FACTURA
ALTER TABLE DETALLE_FACTURA
ADD CONSTRAINT CK_CANTIDAD CHECK (CANTIDAD >= 0)

--RESTRICCIONES PARA FACTURACIÓN
ALTER TABLE ENCABEZADO_FACTURA
ADD CONSTRAINT DF_FECHA_FACTURA DEFAULT CAST(GETDATE() AS DATE) FOR FECHA
ALTER TABLE ENCABEZADO_FACTURA
ADD CONSTRAINT CK_TOTAL_FACTURA CHECK (TOTAL >= 0);
 
 --RESTRICCIONES PARA PAGOS
 ALTER TABLE PAGOS
ADD CONSTRAINT CK_METODO_PAGO CHECK (METODO_PAGO IN ('EFECTIVO', 'TARJETA', 'SINPE'));
ALTER TABLE PAGOS
ADD CONSTRAINT DF_HORA_PAGOS DEFAULT CAST(GETDATE() AS TIME) FOR HORA;
ALTER TABLE PAGOS
ADD CONSTRAINT CK_ESTADO_PAGO CHECK (ESTADO_PAGO IN ('PAGADO', 'DEBE'));

-- Generar registros para la tabla CARGOS
INSERT INTO CARGOS (ID_CARGO, CARGO) VALUES 
(1,'Barista'),
(2,'Caja'),
(3,'Mesas'),
(4,'Administrar'),
(5,'Ayudar'),
(6,'Limpiar'),
(7,'Repartir');

-- Insertar registros en la tabla PRODUCTOS
INSERT INTO PRODUCTOS (NOMBRE_PRODUCTO, DESCRIPCION, CANTIDAD_EN_STOCK, UNIDAD, PRECIO_UNITARIO) VALUES
('Expresso', 'Pequeño', 0.0, 'Onza', 75.00),
('Expresso', 'Mediano', 0.0, 'Onza', 75.00),
('Expresso', 'Grande', 0.0, 'Onza', 75.00),
('Negro', 'Pequeño', 0.0, 'Onza', 75.00),
('Negro', 'Mediano', 0.0, 'Onza', 75.00),
('Negro', 'Grande', 0.0, 'Onza', 75.00),
('Latte', 'Pequeño', 0.0, 'Onza', 75.00),
('Latte', 'Mediano', 0.0, 'Onza', 75.00),
('Latte', 'Grande', 0.0, 'Onza', 75.00),
('Cappuccino', 'Pequeño', 0.0, 'Onza', 75.00),
('Cappuccino', 'Mediano', 0.0, 'Onza', 75.00),
('Cappuccino', 'Grande', 0.0, 'Onza', 75.00),
('Mocha', 'Pequeño', 0.0, 'Onza', 75.00),
('Mocha', 'Mediano', 0.0, 'Onza', 75.00),
('Mocha', 'Grande', 0.0, 'Onza', 75.00),
('Con Leche', 'Pequeño', 0.0, 'Onza', 75.00),
('Con Leche', 'Mediano', 0.0, 'Onza', 75.00),
('Con Leche', 'Grande', 0.0, 'Onza', 75.00),
('Brew', 'Pequeño', 0.0, 'Onza', 75.00),
('Brew', 'Mediano', 0.0, 'Onza', 75.00),
('Brew', 'Grande', 0.0, 'Onza', 75.00),
('Irish', 'Pequeño', 0.0, 'Onza', 75.00),
('Irish', 'Mediano', 0.0, 'Onza', 75.00),
('Irish', 'Grande', 0.0, 'Onza', 75.00),
('Azúcar', 'Regular', 500, 'Onza', 0.0),
('Leche', 'Líquido', 500, 'Onza', 0.75),
('Crema', 'Polvo', 300, 'Onza', 0.75),
('Pajilla', 'Plástico', 5000, 'Unidad', 0.0),
('Copa', 'Pequeño', 5000, 'Unidad', 0.0),
('Copa', 'Mediano', 3000, 'Unidad', 0.0),
('Copa', 'Grande', 2000, 'Unidad', 0.0),
('Café', 'Grano', 1000, 'Onza', 0.0);


-- Insertar registros en la tabla EMPLEADOS
INSERT INTO EMPLEADOS (NOMBRE_EMPLEADO, DIRECCION, NUMERO_TELEFONO, CORREO_ELECTRONICO, ID_CARGO) VALUES
('Juan Pérez', '123 Calle Principal', '1234567890', 'juan.perez@email.com', 1),
('María Rodríguez', '456 Calle Secundaria', '9876543210', 'maria.rodriguez@email.com', 2);

-- Insertar registros en la tabla CLIENTES
INSERT INTO CLIENTES (NOMBRE_CLIENTE, DIRECCION, NUMERO_TELEFONO, CORREO_ELECTRONICO) VALUES
('Cliente', 'Dirección temporal', '12345678', 'ghost@format.com');




SELECT * FROM PRODUCTOS
SELECT * FROM ENCABEZADO_FACTURA
SELECT * FROM EMPLEADOS
SELECT * FROM CLIENTES
SELECT * FROM DETALLE_FACTURA 
SELECT * FROM PAGOS
SELECT * FROM REGISTRO_SISTEMA
SELECT * FROM CARGOS

SELECT ID_PRODUCTO 
FROM PRODUCTOS 
WHERE (NOMBRE_PRODUCTO = 'Expresso' AND DESCRIPCION = 'Pequeño') 
OR (NOMBRE_PRODUCTO = 'Copa' AND DESCRIPCION = 'Pequeño')
OR (NOMBRE_PRODUCTO = 'Copa' AND DESCRIPCION = 'Mediano')
OR (NOMBRE_PRODUCTO = 'Copa' AND DESCRIPCION = 'Grande')
OR (NOMBRE_PRODUCTO = 'Azucar')
OR (NOMBRE_PRODUCTO = 'Leche')
OR (NOMBRE_PRODUCTO = 'Palillos')
OR (NOMBRE_PRODUCTO = 'Crema')
OR(NOMBRE_PRODUCTO = 'Café');