/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Layer1_Interface;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author djjav
 */
public class frmMaster extends javax.swing.JFrame {

    /**
     * Creates new form frmMaster
     */
    public frmMaster() {
        initComponents();
        // Disable resizing, which also disables the minimize button
        setResizable(false);
        //maximize this screen to full
        this.setExtendedState(frmMaster.MAXIMIZED_BOTH);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mdiScreen = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        mnuDetallesFactura = new javax.swing.JMenuItem();
        mnuEmpleados = new javax.swing.JMenuItem();
        mnuFacturacion = new javax.swing.JMenuItem();
        mnuPagos = new javax.swing.JMenuItem();
        mnuProductos = new javax.swing.JMenuItem();
        mnuDetalles = new javax.swing.JMenuItem();
        mnuEnter = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mdiScreen.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\djjav\\Desktop\\JAVA\\Coffe_Shop_Fase2_JAVA\\src\\resources\\images\\500.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mdiScreen.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout mdiScreenLayout = new javax.swing.GroupLayout(mdiScreen);
        mdiScreen.setLayout(mdiScreenLayout);
        mdiScreenLayout.setHorizontalGroup(
            mdiScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mdiScreenLayout.setVerticalGroup(
            mdiScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mnuArchivo.setText("Configurar");

        mnuClientes.setText("Clientes");
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuClientes);

        mnuDetallesFactura.setText("Detalles Factura");
        mnuDetallesFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDetallesFacturaActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuDetallesFactura);

        mnuEmpleados.setText("Empleados");
        mnuEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEmpleadosActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuEmpleados);

        mnuFacturacion.setText("Encabezado Factura");
        mnuFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFacturacionActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuFacturacion);

        mnuPagos.setText("Pagos");
        mnuPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPagosActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuPagos);

        mnuProductos.setText("Productos");
        mnuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductosActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuProductos);

        mnuDetalles.setText("Registro Sistema");
        mnuDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDetallesActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuDetalles);

        mnuEnter.setText("ENTRADA");
        mnuEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEnterActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuEnter);

        jMenuBar1.add(mnuArchivo);

        mnuSalir.setText("Salir");
        mnuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdiScreen, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdiScreen, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
        frmClientes clientes = new frmClientes();
        mdiScreen.add(clientes);
        Dimension size2 = mdiScreen.getSize();
        //the size of the frame by instance
        Dimension formSize2 = clientes.getSize();
        clientes.setLocation(((int) size2.getWidth() - (int) formSize2.getWidth()) / 2, ((int) size2.getHeight() - (int) formSize2.getHeight()) / 2);
        clientes.show();
    }//GEN-LAST:event_mnuClientesActionPerformed

    private void mnuDetallesFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDetallesFacturaActionPerformed
        frmDetallesFactura pedidos = new frmDetallesFactura();
        mdiScreen.add(pedidos);
        Dimension size2 = mdiScreen.getSize();
        //the size of the frame by instance
        Dimension formSize2 = pedidos.getSize();
        pedidos.setLocation(((int) size2.getWidth() - (int) formSize2.getWidth()) / 2, ((int) size2.getHeight() - (int) formSize2.getHeight()) / 2);
        pedidos.show();
    }//GEN-LAST:event_mnuDetallesFacturaActionPerformed

    private void mnuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEmpleadosActionPerformed
        frmEmpleados empleados = new frmEmpleados();
        mdiScreen.add(empleados);
        Dimension size2 = mdiScreen.getSize();
        //the size of the frame by instance
        Dimension formSize2 = empleados.getSize();
        empleados.setLocation(((int) size2.getWidth() - (int) formSize2.getWidth()) / 2, ((int) size2.getHeight() - (int) formSize2.getHeight()) / 2);
        empleados.show();
    }//GEN-LAST:event_mnuEmpleadosActionPerformed

    private void mnuFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFacturacionActionPerformed
        frmEncabezadoFactura facturacion = new frmEncabezadoFactura();
        mdiScreen.add(facturacion);
        Dimension size2 = mdiScreen.getSize();
        //the size of the frame by instance
        Dimension formSize2 = facturacion.getSize();
        facturacion.setLocation(((int) size2.getWidth() - (int) formSize2.getWidth()) / 2, ((int) size2.getHeight() - (int) formSize2.getHeight()) / 2);
        facturacion.show();
    }//GEN-LAST:event_mnuFacturacionActionPerformed

    private void mnuPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPagosActionPerformed
        frmPagos pagos = new frmPagos();
        mdiScreen.add(pagos);
        Dimension size2 = mdiScreen.getSize();
        //the size of the frame by instance
        Dimension formSize2 = pagos.getSize();
        pagos.setLocation(((int) size2.getWidth() - (int) formSize2.getWidth()) / 2, ((int) size2.getHeight() - (int) formSize2.getHeight()) / 2);
        pagos.show();
    }//GEN-LAST:event_mnuPagosActionPerformed

    private void mnuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductosActionPerformed
        frmProducts products = new frmProducts();
        mdiScreen.add(products);
        //the size of the mdi
        Dimension size = mdiScreen.getSize();
        //the size of the frame by instance
        Dimension formSize = products.getSize();
        products.setLocation(((int) size.getWidth() - (int) formSize.getWidth()) / 2, ((int) size.getHeight() - (int) formSize.getHeight()) / 2);
        products.show();
    }//GEN-LAST:event_mnuProductosActionPerformed

    private void mnuDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDetallesActionPerformed
        frmRegistroSistema detalles = new frmRegistroSistema();
        mdiScreen.add(detalles);
        Dimension size2 = mdiScreen.getSize();
        //the size of the frame by instance
        Dimension formSize2 = detalles.getSize();
        detalles.setLocation(((int) size2.getWidth() - (int) formSize2.getWidth()) / 2, ((int) size2.getHeight() - (int) formSize2.getHeight()) / 2);
        detalles.show();
    }//GEN-LAST:event_mnuDetallesActionPerformed

    private void mnuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_mnuSalirMouseClicked

    private void mnuEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEnterActionPerformed
        frmPlatform detalles = new frmPlatform();
        mdiScreen.add(detalles);
        Dimension size2 = mdiScreen.getSize();
        //the size of the frame by instance
        Dimension formSize2 = detalles.getSize();
        detalles.setLocation(((int) size2.getWidth() - (int) formSize2.getWidth()) / 2, ((int) size2.getHeight() - (int) formSize2.getHeight()) / 2);
        detalles.show();
    }//GEN-LAST:event_mnuEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMaster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane mdiScreen;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuDetalles;
    private javax.swing.JMenuItem mnuDetallesFactura;
    private javax.swing.JMenuItem mnuEmpleados;
    private javax.swing.JMenuItem mnuEnter;
    private javax.swing.JMenuItem mnuFacturacion;
    private javax.swing.JMenuItem mnuPagos;
    private javax.swing.JMenuItem mnuProductos;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables
}
